### ISSUE TITLE
Currency conversion showing only 1 icon

### ISSUE THREAD

**Issue by Spagett1** [tchar/ulauncher-albert-calculate-anything#2]
When using the currency conversion function it will only show a single icon.
![image](https://user-images.githubusercontent.com/77225642/126747121-35f4180e-3a3d-4c1e-9b95-587b1c9451bf.png)

**Comment by tchar** [comment]
Hello,

Looks like the links are not preserved when you clone the repo. The USD currency flag is a symbolic link to US flag.
Looks like git converted USD.svg to a file containting US.svg.
On my computer I am developing locally so it works.

Probably you can confirm this if you copy the US flag to USD currency and restart the launcher.
Also the flags with "time" command should work because they are not symlinks.

```bash
cp ~/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything/images/flags/US.svg \
~/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything/images/flags/USD.svg
```

Now for this to be solved there are 2 ways I guess:
- create copies of all currency flags instead of symlink
- resolve the symlink problem with git

Give me an hour or two shouldn't be that hard to fix

**Comment by tchar** [comment]
Hello again @Laar3 

So I found the issue. If you clone the repo directly to ulauncher extensions through git clone, it works perfectly.
For some reason when you install the extension through ulauncher it doesn't do normal git clone and just copies the contents of the file (in case of symlinks it is the name of the linked file), so you end up with normal text files.

#3 fixes this, please confirm that after you update the extension currency flags are showing.

**Comment by Laar3** [comment]
> Hello again @Laar3
> 
> So I found the issue. If you clone the repo directly to ulauncher extensions through git clone, it works perfectly.
> For some reason when you install the extension through ulauncher it doesn't do normal git clone and just copies the contents of the file (in case of symlinks it is the name of the linked file), so you end up with normal text files.
> 
> #3 fixes this, please confirm that after you update the extension currency flags are showing.

ive updated but now the currency conversion doesnt do anything at all (all other functions work though) after this i tried removing the extension and manually git cloneing to the .local/share/ulauncher/extensions and the currency conversion still wouldnt work

**Comment by Laar3** [comment]
![image](https://user-images.githubusercontent.com/77225642/126887625-fb0c8775-2eb1-4dd0-b290-54521c22fd15.png)
forgot to upload an image

**Comment by tchar** [comment]
@Laar3 

I should create a logger indipendently from ulauncher because it is not enough as the project grew in size.

All right that's a different issue. Now to figure this out I need you to give me some logs.

Before doing that you can check the cache of the extension.

It should be in `~/.cache/extension_calculate_anything/` and normally you can find 2 files there. One of them should be called `currency_data.json`. Can you open that file and confirm the contents with me?

I suspect that the last update timestamp is relatively new and the exchange rates are empty.

If the file is too big you can use this snippet to get the info from `currency_data.json`
```bash
python -c "import os,json;f=open(os.path.expanduser('~/.cache/extension_calculate_anything/currency_data.json'));d=json.loads(f.read());f.close();p=d.get('provider');t=d.get('last_update_timestamp');c=d.get('exchange_rates');print('provider={},timestamp={},currencies={}'.format(p, t, len(c) if c is not None else None))"
```

Normally by deleting the file and restarting ulauncher it should work.

However I would really appreciate it if you provided some logging output so that I can find out what went wrong before deleting the file. In order to do so close ulauncher and open it in dev mode with no extensions
```bash
ulauncher --no-extensions --dev -v |& grep calculate-anything
```

Open a new terminal and type the VERBOSE command you see above. Alternatively you can find this command under the extension's preferences when you open ulauncher in dev mode. Should look like this
```bash
VERBOSE=1 ULAUNCHER_WS_API=ws://127.0.0.1:5054/com.github.brpaz.ulauncher-docsearch PYTHONPATH=/usr/lib/python3/dist-packages /usr/bin/python3 ~/.local/share/ulauncher/extensions/com.github.brpaz.ulauncher-docsearch/main.py
```

Redirect the log to a file by adding `2>&1 | tee ~/ulauncher-calculate-anything.log`. So the final command should look like this.
```bash
VERBOSE=1 ULAUNCHER_WS_API=ws://127.0.0.1:5054/com.github.tchar.ulauncher-albert-calculate-anything PYTHONPATH=/usr/lib/python3/dist-packages /usr/bin/python3 ~/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything/main.py 2>&1 | tee ~/ulauncher-calculate-anything.log
```

You should see some logs in your terminal.
Type the currency conversion and then close the terminal and post the logs over here.

Thanks for taking the time to help me resolve this.
