### ISSUE TITLE
Cannot install the extension

### ISSUE THREAD

**Issue by jrafaaael** [tchar/ulauncher-albert-calculate-anything#28]
## Describe the bug
Cannot install the extension

## To Reproduce
1. Open "Ulauncher Preferences"
2. Enter the "Extensions" tab
3. Select the option "Add extension"
4. Paste the repository link (https://github.com/tchar/ulauncher-albert-calculate-anything)

## Expected behavior
Extension installed

## Logs
Message: undefined
Error Name: undefined
Type: undefined

Stacktrace:
```
undefined
```

## Desktop (please complete the following information)
 - OS: [Ubuntu Mate 20.04 ]
 - Linux: Ubuntu 20.04.2 LTS

**Comment by tchar** [comment]
@jrafaaael Have you installed the dependencies?

```
Pint==0.17
simpleeval==0.9.10
parsedatetime==2.6
pytz==2021.1
```

Also this problems really looks like a [Ulauncher](https://github.com/Ulauncher) problem because I have similar problems myself. Right now I can reproduce your issue and for some reason if I restart Ulauncher the extension works properly. Consider doing the following and report back please

1. Run `pip install Pint simpleeval parsedatetime pytz`
2. Restart `Ulauncher` and see if the extension works
3. If step 2 fails try downloading the extension manually with the following

**Warning this method should disable future updates, just a check if it is ulauncher's problem or not. If this works, then remove the folder and try installing through ulauncher**

```bash
rm -r ~/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything/
git clone https://github.com/tchar/ulauncher-albert-calculate-anything ~/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything
```

After confirming it works
```bash
rm -r ~/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything/
git clone https://github.com/tchar/ulauncher-albert-calculate-anything 
```

And install through Ulauncher, restart launcher if necessary.

I strongly believe this is a Ulauncher issue
Here is a video showing the same problem as yours but after restarting launcher, the extension is there and working

https://user-images.githubusercontent.com/6424426/129417819-92575a92-877b-4448-aca1-b1bf4a8c9d35.mp4

Here is a similar issue where `Ulauncher` says the extension has crashed but in reality it is working.

https://user-images.githubusercontent.com/6424426/129417837-b4545082-eb58-4afa-a23c-18c761a3b304.mp4
