### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by guillaumevauvert-datadome** [tchar/ulauncher-albert-calculate-anything#33]
## Describe the bug
Despite to have installed all required dependencies, I have still the issue:

> looks like parsedatetime is not installed 

## To Reproduce
- Install this extension.
- Type "time"

## Expected behavior
I can use the extension.

## Logs
Nothing interesting in logs.

## Screenshots
```
pip show pint simpleeval parsedatetime pytz
Name: Pint
Version: 0.17
Summary: Physical quantities module
Home-page: https://github.com/hgrecco/pint
Author: Hernan E. Grecco
Author-email: hernan.grecco@gmail.com
License: BSD
Location: /home/guillaumevauvert/.local/lib/python3.6/site-packages
Requires: importlib-metadata, importlib-resources, packaging
Required-by: 
---
Name: simpleeval
Version: 0.9.11
Summary: A simple, safe single expression evaluator library.
Home-page: https://github.com/danthedeckie/simpleeval
Author: Daniel Fairhead
Author-email: danthedeckie@gmail.com
License: UNKNOWN
Location: /home/guillaumevauvert/.local/lib/python3.6/site-packages
Requires: 
Required-by: 
---
Name: parsedatetime
Version: 2.6
Summary: Parse human-readable date/time text.
Home-page: https://github.com/bear/parsedatetime
Author: Mike Taylor
Author-email: bear@bear.im
License: Apache License 2.0
Location: /home/guillaumevauvert/.local/lib/python3.6/site-packages
Requires: 
Required-by: 
---
Name: pytz
Version: 2021.1
Summary: World timezone definitions, modern and historical
Home-page: http://pythonhosted.org/pytz
Author: Stuart Bishop
Author-email: stuart@stuartbishop.net
License: MIT
Location: /home/guillaumevauvert/.local/lib/python3.6/site-packages
Requires: 
Required-by: 
```

## Desktop (please complete the following information)
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by tchar** [comment]
Hello @guillaumevauvert-datadome

1. what happens if you type time?
2. Did you setup specific default cities? Like for example if you type `time at Delhi`, does it work or just the `time` command has problems.
3. If you re-install the extension, does the problem persist?

Thanks for reporting the problem.

**Comment by guillaumevauvert-datadome** [comment]
Hello @tchar 
1. I have the error immediately (looks like parsedatetime is not installed)
2. No default city. The issue happens as soon as time is typed.
3. Yes
It may be due to where python libs are installed. /home/guillaumevauvert/.local/lib/python3.6/site-packages ?

**Comment by tchar** [comment]
Hmmm the user python packages should work.

Assuming you did install parsedatetime with
```bash
pip install parsedatetime
```

Do you by any chance have multiple python versions and for some reason ulauncher uses a different one?
So if for example ulauncher is not launched with python3.6 but another version, that might be the problem.
Also you can try
```bash
sudo pip install ....
```

To see if this can fix it.

Also. Can you try running the `prompt.py` file from https://github.com/tchar/ulauncher-albert-calculate-anything/blob/master/misc/prompt.py?

The reason I am asking is because prompt.py basically uses the plugin with python prompt_toolkit. If this works, then it is an indication that another python version runs for ulauncher instead of python3.6
